### ISSUE TITLE
Using this with 2 64x64 chained

### ISSUE THREAD

**Issue by jlodge10** [c0wsaysmoo/plane-tracker-rgb-pi#11]
I am trying to use this with 2 64x64 matrixes chained together but am only getting things displayed properly on the top half of one screen. I went in /setup/screens and changed the height to 64 and went to /display/__init__ and changed the rows to 64 and the chain length variable to 2, but can't find any other places to change the size.

**Comment by c0wsaysmoo** [comment]
Hey
Everything is hard coded for a 64*32 resolution ie the logos are sized
16*16 etc. You'd have to change all the formats (font/image size etc) to
accommodate a larger setup.

**Comment by jlodge10** [comment]
Thanks for the response. Do you have the website where you got the logos from so I can scale them down to 32x32 instead of 16x16?

**Comment by c0wsaysmoo** [comment]
No, I was able to get most from flight aware but the others I added
manually or found in other collections.
