### ISSUE TITLE
Is it possible to build a version for Raspberry Pi with 3.5" TFT screen?

### ISSUE THREAD

**Issue by yknet86** [c0wsaysmoo/plane-tracker-rgb-pi#3]
Hi, thank you for your wonderful work! However, I did not own a RGB device, is it possible to build a version to use with the 3.5" TFT screen instead of the RGB?  Appreciated for your consideration.

TFT screen  (http://www.lcdwiki.com/MHS-3.5inch_RPi_Display), it has own driver just display as hdmi output.

**Comment by c0wsaysmoo** [comment]
Hey
It might be possible however it would be completely different as the
resolution to your screen is 480 x320 and the resolution on the RGB panel
is 64x32 among other issues. it's not set up for a regular screen, it would
require heavy modification, all new high res icons, and complete different
display code.  Good luck!
