### ISSUE TITLE
Adding altitude

### ISSUE THREAD

**Issue by samsonpwnz** [c0wsaysmoo/plane-tracker-rgb-pi#5]
Would it be possible to show current altitude of flight being tracked so that it shows up on display?
Thanks for your work!

**Comment by c0wsaysmoo** [comment]
Hey! you certainly could show current altitude however not sure where you
would show it or what you would want to replace with it. You would just add
it to the overhead code in the utilities file and then modify one of the
scene files to display it

**Comment by samsonpwnz** [comment]
Thanks for the reply, I was looking through the code, but not knowing python it mostly seems to be going over my head.
I just wanted to add altitude and show it under the miles display or just append to end of the ticker that shows flight info.
