### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by boxcar32** [c0wsaysmoo/plane-tracker-rgb-pi#7]
Hi and thanks for your efforts in making this. I had this working for months until yesterday. I reinstalled everything and now getting "PermissionError: [Errno 13] Permission denied: '/home/pi/icons/{icon}.png'". I have googled for answers but no luck.

**Comment by c0wsaysmoo** [comment]
ya the problem i think is you installed it originally with Linux bullseye and now you installed bookworm which requires a different set of instructions

**Comment by boxcar32** [comment]
Thank you c0wsaysmoo! That was the issue, It's now working again.
