### ISSUE TITLE
path of the files

### ISSUE THREAD

**Issue by cfl2002** [c0wsaysmoo/plane-tracker-rgb-pi#9]
copied over the folders but getting the error messages for when try to access folders. see below.  thanks

mv /home/path/plane-tracker-rgb-pi/* /home/path/
mv: cannot stat '/home/path/plane-tracker-rgb-pi/*': No such file or directory

**Comment by c0wsaysmoo** [comment]
are you using the path or "path"

**Comment by cfl2002** [comment]
I am using the word "path". I am new, where can I locate the path?

**Comment by c0wsaysmoo** [comment]
Reread step 3

**Comment by cfl2002** [comment]
mv /home/ted/plane-tracker-rgb-pi/* /home/ted/
mkdir /home/ted/logos
mv /home/ted/logo/* /home/ted/logos/
mv /home/ted/logo2/* /home/ted/logos/

ted is pi name

**Comment by c0wsaysmoo** [comment]
"cd" then enter, then "ls" then enter and itll tell you what folders are there

**Comment by cfl2002** [comment]
ted2@raspberrypi:~ $ ls
icons               logo2                 README.md
its-a-plane-python  logos                 rgb-matrix.sh
logo                plane-tracker-rgb-pi  rpi-rgb-led-matrix

**Comment by c0wsaysmoo** [comment]
Looks like it's already there

**Comment by cfl2002** [comment]
how should I make changes to these, what is the command?

ted@raspberrypi:~ $ /home/ted/its-a-plane-python/its-a-plane.pyTraceback (most recent call last):
  File "/home/ted/its-a-plane-python/its-a-plane.py", line 2, in <module>
    from display import Display
  File "/home/ted/its-a-plane-python/display/__init__.py", line 5, in <module>
    from utilities.overhead import Overhead
  File "/home/ted/its-a-plane-python/utilities/overhead.py", line 6, in <module>
    from config import DISTANCE_UNITS
  File "/home/ted/its-a-plane-python/config.py", line 2, in <module>
    "tl_y": xx.xxxxxx, # Top-Left Latitude (deg) https://www.latlong.net/ the bigger the zone, the more planes you'll get
            ^^
NameError: name 'xx' is not defined

**Comment by c0wsaysmoo** [comment]
I have written out the instructions as best I can, I am not going to spend
my night and literally tell you how to make every step. use google. I just
made one tonight using the exact instructions I have posted.

**Comment by c0wsaysmoo** [comment]
hey,
yup you have to attach to SCL and GND and then you have to run the code and
then it should work!
